apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-redis-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/refresh: "true"
    argocd.argoproj.io/external-url: "http://127.0.0.1:5000/"
spec:
  project: default
  source:
    repoURL: 'https://github.com/RAMON1743/flask-redis-counter-Practica-RamonMeza.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  info:
    - name: "Application URL"
      value: "http://127.0.0.1:5000/"
