apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-redis-counter
  namespace: default
  labels:
    app: flask-redis-counter
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask-redis-counter
  template:
    metadata:
      labels:
        app: flask-redis-counter
    spec:
      containers:
        - name: flask-app
          image: ramon1743/flask-redis-counter-practica-ramonmeza:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: flask-redis-config
            - secretRef:
                name: flask-redis-secret
