apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-redis-counter
  namespace: default
  labels:
    app: flask-redis-counter
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask-redis-counter
  template:
    metadata:
      labels:
        app: flask-redis-counter
    spec:
      automountServiceAccountToken: false  # 🔹 Evita la asignación automática de credenciales RBAC
      volumes:
        - name: flask-storage
          persistentVolumeClaim:
            claimName: flask-pvc  # 🔹 Uso del PVC para almacenamiento persistente
      containers:
        - name: flask-app
          image: ramon1743/flask-redis-counter-practica-ramonmeza:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: flask-redis-config
            - secretRef:
                name: flask-redis-secret
          resources:
            requests:
              memory: "128Mi"  
              cpu: "250m"       
            limits:
              memory: "256Mi"  
              cpu: "500m"       
          volumeMounts:
            - mountPath: /app/storage
              name: flask-storage  
