apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-redis-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-redis-counter
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # 📌 Escala si el uso de CPU supera el 70%
