apiVersion: v1
kind: Service
metadata:
  name: flask-redis-counter-service
spec:
  selector:
    app: flask-redis-counter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
