apiVersion: v1
kind: Service
metadata:
  name: flask-redis-counter-service
  namespace: default
  labels:
    app.kubernetes.io/instance: flask-redis-app
  annotations:
    endpointslice.kubernetes.io/skip: "true" 
    link.argocd.argoproj.io/external-link: "http://127.0.0.1:5000/"
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      nodePort: 32293
  selector:
    app: flask-redis-counter
